### PR TITLE
whitespace and quoting fixes in json and yaml examples (v3.2.0)

### PR DESCRIPTION
**Pull request by karenetheridge**
same as https://github.com/OAI/OpenAPI-Specification/pull/3465

### CODE REVIEW

**Review by SyedAmbro — APPROVED** [review]
- [ ]

**Review by darrelmiller — APPROVED** [review]

**Comment by karenetheridge** [comment]
rebased.

**Comment by mikekistler** [comment]
Question on this: Can we establish our conventions for whitespace and quoting and then enforce them in the PR pipeline? I'm just thinking that we don't want to have to fix this again in 6 months.

**Comment by karenetheridge** [comment]
rebased!

**Pull request merged**
