### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cyberhicham**
typo

### CODE REVIEW

**Comment by darrelmiller** [comment]
fka stands for "formerly known as" whereas "aka" stands for "also known as", which is not the case.  What used to be the Swagger specification is no longer known as that.  It is now known as "OpenAPI Specification.

**Comment by cyberhicham** [comment]
Oops, my bad !

**Comment by ePaul** [comment]
Though maybe we should write this phrase out?

**Comment by cyberhicham** [comment]
Maybe, as this is the first time I saw fka (feels wrong for me ^^)

**Pull request closed without merging**
