### PR TITLE
Fixed servers type

### LINKED ISSUE #973: 3.0.0-rc0 inconsistent 'servers' fields
[Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#operationObject) has a fixed field called `servers` which expects a _single_ [Server Object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#serverObject) as it's value. It's description is a little contradictory.

> An alternative server **array** to service this operation. If an alternative server **object** is specified at the Path Item Object or Root level, it will be overridden by this value.

[Path Item](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#pathItemObject) is the same as it also has a fixed field named `servers`, but is shown as a single object.

Shouldn't both Operation Object and Path Item Object have their `servers` field denoted as `[Server Object]`?

Assuming servers are supposed to implicitly _inherit_ from their parent object if not defined I think the descriptions could be made more consistent. Something like:

OpenAPI Object
> An optional array of Server Objects which provide connectivity information to a target server.

Path Item Object
> An optional array of Server Objects which provide connectivity information to a target server.
If a server array is specified at the OpenAPI Object level, it will be overridden by this value.

Operation Object
> An optional array of Server Objects which provide connectivity information to a target server.
If a server array is specified at the Path Item Object or OpenAPI Object level, it will be overridden by this value.

### PR DESCRIPTION
**Pull request by webron**
Resolved #973

### CODE REVIEW

**Comment by RobDolinMS** [comment]
@darrelmiller Would you please give this a quick review?  It's a two-line change.  Thanks.

**Comment by whitlockjc** [comment]
:shipit:

**Comment by darrelmiller** [comment]
Whoa.  I was not expecting this change.  I thought the `servers` was the typo and we were only going to allow a single server overload.

**Comment by darrelmiller** [comment]
Ok, I withdraw my concerns.  Even with one server, a spec could define different variables at the path item/operation level and require the user to provide different input.  So, let's just be consistent.

**Pull request merged**
