### PR TITLE
Add link to one more implementation

### PR DESCRIPTION
**Pull request by yvasiyarov**
Just add link to one more swagger spec generator. It analyse code comments and automatically generate swagger spec by this comments and Go type definitions.

### CODE REVIEW

**Comment by webron** [comment]
@yvasiyarov - can I get your email please? Looking to contact library developers directly. You can send it to me by email if you prefer, email in profile.

**Comment by yvasiyarov** [comment]
@webron sent you an email

**Comment by webron** [comment]
Looks like I didn't get it, can you send again please?

**Comment by yvasiyarov** [comment]
varyous at gmail.com

**Pull request merged**
