### PR TITLE
TOB members 2019

### PR DESCRIPTION
**Pull request by ncaidin**
To reflect the latest TOB elections.

### CODE REVIEW

**Comment by ncaidin** [comment]
@OAI/tsc  could you please review my pull request?

**Comment by usarid** [comment]
@ncaidin I may well be too pedantic here, but when I read

> and any cross-project or high-level issues that cannot be resolved in the TSC for the OAS

I worry that someone might interpret this as being the governing body, vs the BGB. Changing the charter, for example, is a cross-project high-level issue, but should not be done by the TOB. So should we somehow constrain this language?

**Comment by ncaidin** [comment]
Thanks @usarid .

I simply did a copy/paste from the Charter to make sure it was consistent. Please bear in mind that the TOB has been invoked zero times since OAI has been formed. I think the part where it says "in the TSC"  makes it clear. The TOB is intended to resolve conflicts that the TSC can not in order to avoid having to go to the BGB. 

What if I change it to this:
"The TOB is responsible for managing conflicts, violations of procedures or guidelines or other issues that cannot be resolved in the TSC for the OAS. For further details please consult the OpenAPI Project Charter."

Personally I would be okay keeping the language as is or changing to this. Also open to other suggestions, but suggest we KIS (keep it simple). 

What do you think?

**Comment by usarid** [comment]
The new language sounds great to me. Thanks!


________________________________

**Comment by ncaidin** [comment]
@usarid  text updated. Thanks for your review.

**Comment by ncaidin** [comment]
@usarid , is there anything else I need to do to get this PR approved and merged?

**Comment by ncaidin** [comment]
@OAI/tsc  is there anything more that needs to be done with the request to get it approved and merged? 

Thanks.

**Pull request merged**
