### PR TITLE
Fixing license in schema v2.0 package.json.

### PR DESCRIPTION
**Pull request by jsdevel**

### CODE REVIEW

**Comment by webron** [comment]
If anything, it should be fixed to APL2.0 ;) but thanks.

**Comment by jsdevel** [comment]
Just making it conform to `bower.json` and the `README`

**Comment by jsdevel** [comment]
I can switch them all to `APL` if you prefer.

**Comment by webron** [comment]
That would be great, thanks. That's the official license intended to be used. And to make sure, the intent is the Apache 2.0 License, not the Adaptive Public License.

**Comment by jsdevel** [comment]
done

**Pull request merged**
