### PR TITLE
fix: rename wrong operationId find pet by id to findPetById

### PR DESCRIPTION
**Pull request by exfly**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Please could you add some context as to why you believe this `operationId` is wrong?

**Comment by exfly** [comment]
other codebase operationID is something like addPet, this wrong operationID is `find pet by id`, so I think this is wrong, isn't it?

**Comment by MikeRalphson** [comment]
> other codebase operationID is something like addPet, this wrong operationID is find pet by id, so I think this is wrong, isn't it?

No, the only restriction on an `operationId` is that it must be unique, there are no constraints on the format of the string.

Tooling should take appropriate steps to be able to use `operationId`s in various casings and spacings.

**Comment by MikeRalphson** [comment]
@OAI/tsc Motion to close?

**Comment by MikeRalphson** [comment]
Closing as not an error.

**Pull request closed without merging**
