### PR TITLE
Fix content of Path Item Object link

### PR DESCRIPTION
**Pull request by char0n**
This change allows to detect this occurence of Path Item Object
with native browser search capability.

Signed-off-by: Vladimir Gorej <vladimir.gorej@gmail.com>

### CODE REVIEW

**Review by MikeRalphson — CHANGES_REQUESTED** [review]
Thanks, this PR looks great from a consistency point of view. Could you please re-target it to `versions/3.1.1.md` on the `v3.1.1-dev` branch?

**Comment by char0n** [comment]
@MikeRalphson branch updated.

**Comment by webron** [comment]
Might need to re-create the PR and submit it. Since it was originally done on the `main` branch, the PR now pulls quite a few changes from `main` to `v3.1.1-dev` which hide the true change in the PR. It's best if we keep sync PRs separately.

**Comment by char0n** [comment]
Closing in favor of https://github.com/OAI/OpenAPI-Specification/pull/2643

**Pull request closed without merging**
