### PR TITLE
Operation Level Tags must be unique, Fix For Issue 1727

### PR DESCRIPTION
**Pull request by r-sreesaran**
Operation Level Tags must be unique, Fix For Issue 1727

### CODE REVIEW

**Comment by earth2marsh** [comment]
Rather than being so strict as to potentially break existing specs, could we add guidance like, "Duplicate tags MAY be considered an authoring mistake"?

**Comment by handrews** [comment]
@MikeRalphson 

> Rather than being so strict as to potentially break existing specs, could we add guidance like, "Duplicate tags MAY be considered an authoring mistake"?

I'm fond of "The behavior of X is undefined" 😛

**Comment by r-sreesaran** [comment]
@earth2marsh  considering the fact it will break existing code changes, this may be the only way forward.

**Comment by earth2marsh** [comment]
Based on my rationale in #1727 , I'm inclined to close this issue without merging, though I would also like to recognize the author's contribution to the process--thank you!

**Comment by lornajane** [comment]
Closing as I don't see a consensus to accept/merge this. I'll second the acknowledgement of the contribution though! Thanks!

**Pull request closed without merging**
