### PR TITLE
[master] Validate (not lint) markdown files

### PR DESCRIPTION
**Pull request by MikeRalphson**
Checks for broken links and missing img alt tags ~~and fenced code-blocks with no defined language~~.

This change also updates the Node.js version used on Travis from 0.10.36 which is now unsupported, to a LTS version (6.x)

Issues identified have been fixed.

### CODE REVIEW

**Comment by webron** [comment]
I'd rather keep the changes to 1.2 and 2.0 to a minimum. The broken links don't change any of the meaning of the spec and are not 100% required. We'll discuss that and decide if we want to make these changes.

**Comment by MikeRalphson** [comment]
@webron sure, there is an argument that if no-one's noticed up till now, they're not needed. I was just thinking ahead for when v3 gets merged into master.

**Comment by webron** [comment]
Yeah, I like the idea of adding it to 3.0 to avoid such issues from now on. Thanks for the pulling this together.

**Comment by RobDolinMS** [comment]
@MikeRalphson - It looks like there is now a conflict.  Would you be able to resolve?

**Comment by MikeRalphson** [comment]
@RobDolinMS done.

**Comment by webron** [comment]
Sorry for the trouble, @MikeRalphson. I'd rather not merge this for now given the reasons above. Appreciate the work though. We might revisit it in the future and could just reopen and merge.

**Pull request closed without merging**
