### PR TITLE
Permit tooling to limit commonmark usage

### PR DESCRIPTION
**Pull request by darrelmiller**
Addresses issue #1078

### CODE REVIEW

**Comment by RobDolinMS** [comment]
LGTM.  Is this ready to merge?

**Comment by fehguy** [comment]
I want a pony

**Comment by whitlockjc** [comment]
When I read this wording, I read it as if I have to render CommonMark a certain way and I'm not sure that's how we want to do it.  I think for us to mark things as compliant, we're saying that we should treat values that are valid CommonMark 0.27 as valid whether or not you render it, or how you render it.  But I do get what you're proposing from the security perspective where those choosing to render HTML can choose to limit some features of CommonMark 0.27 for security purposes.

I'll give it some thought and see if I can come up with any suggestions.

**Comment by webron** [comment]
Covered on the call - suggestion was to limit the wording to the impact on rendering. The wording right now implies that a command-line tool (for example) would require to support CommonMark in order to be compliant, however, it has no real impact on the tool.

**Comment by RobDolinMS** [comment]
I was thinking about @whitlockjc's comments on this from today's TDC and wondering if something like this would address people's concerns:

OpenAPI compliant tooling MUST NOT break if markdown that is compliant with CommonMark 0.27 is used as the value of the description field.

Tool authors MAY choose to do any of:
* Implement rendering for ALL of CommonMark 0.27
* Implement rendering for SOME of CommonMark 0.27 (ex: ignore <script> tags)
* Implement rendering for NONE of CommonMark 0.27 (ex: ignore any description value that is not plain text)

/cc @darrelmiller @fehguy

**Comment by DavidBiesack** [comment]
I don't think OAS should overly specify the behavior (i.e. only provide only those three options. There are gradations of support - i.e. strip all HTML / CommonMark markup and leave just the text would not be allowed if phrased as above. I prefer the existing language in the PR, "Tooling MAY limit some CommonMark features to address security concerns." (but was unable to participate in the TDC call so I don't know how the discussion went) although as far as a specification is concerned, a small change might be to state "Tooling MAY limit some or all CommonMark features to address security concerns."

**Comment by darrelmiller** [comment]
I have updated the text to try and address concerns raised in the TDC call.

- Clarified that compatibility with CommonMark is only relevant for tooling that renders rich text.  
- Clarified that tooling is not limited to only supporting CommonMark .27 features. Other newer features can be supported
- Clarified that tooling should only ignore and not fail when features with security concerns are used.

/cc @OAI/tdc

**Comment by webron** [comment]
:shipit:

**Comment by earth2marsh** [comment]
LGTM

**Pull request merged**
