### PR TITLE
docs(Components): fix typo in schemas field type

### PR DESCRIPTION
**Pull request by char0n**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks for this, could you change the base branch to `v3.1.0-dev` please?

**Comment by char0n** [comment]
@MikeRalphson I'll have to resubmit the PR then. Just changing the base branch creates a lot of mess.

**Comment by MikeRalphson** [comment]
Thank you, that would be appreciated.

**Comment by char0n** [comment]
@MikeRalphson changes rebased on top of `v3.1.0-dev` now.

**Review by webron — APPROVED** [review]

**Pull request merged**
