### PR TITLE
Rename 2.0.md to 2.0.mdtransfers?max_page_size=20&blockchain_id=32RKL…

### PR DESCRIPTION
**Pull request by leonmende**
…HE7pvKuaiSYi4toR4xj4JggTAinEJ-mainnet&address=32RKLHE7pvKuaiSYi4toR4xj4JggTAinEJ%2C32RKLHE7pvKuaiSYi4toR4xj4JggTAi

transfers?max_page_size=20&blockchain_id=32RKLHE7pvKuaiSYi4toR4xj4JggTAinEJ-mainnet&address=32RKLHE7pvKuaiSYi4toR4xj4JggTAinEJ%2C32RKLHE7pvKuaiSYi4toR4xj4JggTAi

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Perhaps this PR was raised in error? It doesn't look like something we would merge.

**Comment by leonmende** [comment]
Hola me puede esplicar por favor

**Comment by leonmende** [comment]
Hola esplicame por favor que hice mal y si me puedes ayudar?

**Comment by MikeRalphson** [comment]
This PR appears to rename a fixed version of the OpenAPI specification to a filename which would:

* break people's links
* break GitHub language recognition and syntax highlighting
* incorporates what looks like URL parameters related to a blockchain address

**Comment by leonmende** [comment]
Solo quiero cambiar mis monedad

**Comment by MikeRalphson** [comment]
I don't think we can help you with that.

**Comment by leonmende** [comment]
Ok  pero tengo mi direcciones y lo que pasó fue que al borrar una palabra
no se borró todo

**Comment by leonmende** [comment]
Lo corregí bien????

**Pull request closed without merging**
