### PR TITLE
Fix JSON media type example

### PR DESCRIPTION
**Pull request by floitsch**

### CODE REVIEW

**Review by handrews — APPROVED** [review]
Thanks!  These look straightforward.  There is a bit of a process question to resolve regarding deployment, and also synchronizing JSON and YAML versions, see #3516 for tracking that sort of thing.

**Comment by handrews** [comment]
@floitsch I just realized that while you got the branch right 🎉 this would need to be on the `versions/3.1.1.md` file rather than the `versions/3.1.0.md`.  We only update published specs for broken links (yes, it's been considered to update this sort of formatting error as well, but... there's a big conversation there and for now that is not the policy- we're still figuring out how to deploy the broken link fixes as allowing that change is a new policy).

If you could update this to change `3.1.1.md` and not `3.1.0.md` we'll be happy to merge it.

**Comment by handrews** [comment]
Does this also need to go into 3.0.4?

**Comment by handrews** [comment]
@floitsch I'm assuming that since it took us nearly 3 months to respond to this that you understandably aren't monitoring it now.  I've re-submitted this on your behalf for both 3.1.1 (#3546) and 3.0.4 (#3547), retaining a credit to you in the commit.  Please feel free to comment here if you'd rather re-submit yourself and just hadn't gotten around to it.

Thank you for the contribution!

**Comment by floitsch** [comment]
> @floitsch I'm assuming that since it took us nearly 3 months to respond to this that you understandably aren't monitoring it now. I've re-submitted this on your behalf for both 3.1.1 (#3546) and 3.0.4 (#3547), retaining a credit to you in the commit. Please feel free to comment here if you'd rather re-submit yourself and just hadn't gotten around to it.

I was a bit busy and only managed to look at it today. Nice surprise to see it already done :)

No need for the attribution/credit. The important thing is that the code-base gets improved.
Thanks for porting.

**Pull request closed without merging**
