### PR TITLE
Revised typo and language to MAY

### PR DESCRIPTION
**Pull request by jameswatts**

### CODE REVIEW

**Comment by darrelmiller** [comment]
👍

**Comment by webron** [comment]
I'm ok with fixing the typo, a bit less inclined to change the wording (as minor as it may be). Would much rather concentrate on fixing relevant wording issues in 3.0.

**Comment by jameswatts** [comment]
@webron should I revise the PR to remove the language change?

**Comment by webron** [comment]
If you don't mind. And feel free to submit something similar (with the revised language if applicable) to 3.0 so we won't forget there.

**Comment by jameswatts** [comment]
@webron done.

**Comment by jameswatts** [comment]
Proposed language update for **3.0** here: #760

**Pull request merged**
