### PR TITLE
[Implementations] Add AutoRest

### PR DESCRIPTION
**Pull request by RobDolinMS**
Add AutoRest to the list of code generators 
Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by RobDolinMS** [comment]
Setting milestone to v3.Next as this is not required for v3.0.0.

**Comment by RobDolinMS** [comment]
TDC: @webron Please review this one line change and merge if it looks good.

**Comment by RobDolinMS** [comment]
#TDC: @webron  to review and merge

**Comment by webron** [comment]
@RobDolinMS Can you help me find an indication to Autorest working on 3.0 support?

**Comment by RobDolinMS** [comment]
#TDC: @darrelmiller and @robdolinms to add pointers to work going on in AutoRest and TypeScript

**Pull request closed without merging**
