### PR TITLE
Add templated-url format to the registry

### PR DESCRIPTION
**Pull request by MikeRalphson**
As discussed with @jdesrosiers on Slack

### CODE REVIEW

**Comment by handrews** [comment]
(pardon muddled thoughts - I'm recovering from COVID) is there a reason to not make this `oas-templated-url`?  There might be a wide range of formats that fit the vague description here, making the format difficult to support.

**Comment by MikeRalphson** [comment]
There's no reason not to, is it just for clarity? AsyncAPI might use something very similar though.

**Comment by handrews** [comment]
trying to avoid a repeat of `decimal` where there are different meanings depending on context

**Comment by handrews** [comment]
i think the question to ask is: what guarantees can tools assume/implement when they see this format?  Currently, not much.  URI + `{` and `}`, but that is a broader constraint than OAS defines - OAS puts constraints on what parts of a URI can be replaced by a variable, and might constrain the variable syntax (I can't recall)

**Comment by handrews** [comment]
See also #3256 (Formally define templating behavior)

**Comment by handrews** [comment]
I think if we make this `oas3-templated-url` we could merge it.  That avoids confusion with other URL templating systems, of which there are many, including ones that differ across OAS versions.

**Comment by handrews** [comment]
Also, I think this needs rebasing.

**Comment by handrews** [comment]
Since Mike's not available to rebase and discuss this, and we're already tracking the need for a format for this in #3530 (which already links to this PR), I'm just going to close this.  When someone is available to figure it out they can submit a new PR.

**Pull request closed without merging**
