### PR TITLE
Fixed 2 times 'are' typo

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
Please review @darrelmiller @jharmn.

**Comment by webron** [comment]
@andriisoldatenko we're going to publish more instructions about the next steps of the spec including submitting PRs. In general, we will not accept PRs against `master` directly to the spec as the spec cannot change. I imagine we'll create a 3.0.1.md in the OpenAPI.next branch for such changes.

**Comment by andriisoldatenko** [comment]
should i wait for new branch? I just want to help with text :)

**Comment by webron** [comment]
Thanks for your patience, @andriisoldatenko. Please resubmit the fix against the [v3.0.1](https://github.com/OAI/OpenAPI-Specification/tree/v3.0.1) branch to the new file.

**Comment by andriisoldatenko** [comment]
@webron done in https://github.com/OAI/OpenAPI-Specification/pull/1330

**Pull request closed without merging**
