### PR TITLE
Add Microsoft VS Code OAS 3.0 extension

### PR DESCRIPTION
**Pull request by DSotnikov**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks. The language column is intended to help users find projects *written* in particular languages (especially to find projects to collaborate on), so "Any" isn't really helpful, though I gather this project may be semi- closed-source (source available). Is TypeScript more appropriate?

I'm also hesitant to add projects which do not support OAS 3.0's requirement that both JSON and YAML forms be supported. I'm aware that this is on your roadmap.

**Comment by DSotnikov** [comment]
Thanks, Mike! I've changed the language field as requested. 

YAML support comes within days now - so feel free to wait a little. I will add a comment to this thread once the extension gets updated with the feature.

**Comment by DSotnikov** [comment]
Hi, Mike, YAML support is in the extension now.

**Comment by DSotnikov** [comment]
@MikeRalphson, anything else you need from me at this point to merge the pull request?

I have fixed the Language field, and we have added YAML support to the tool.

**Comment by DSotnikov** [comment]
@MikeRalphson Is there anything preventing you from merging the PR now?

I can issue a new PR if that makes things easier. Just let me know.

**Pull request merged**
