### PR TITLE
Specification Extension instead of Vendor Extension

### PR DESCRIPTION
**Pull request by ralfhandl**
#643 for V3.0

### CODE REVIEW

**Comment by DavidBiesack** [comment]
:+1:

**Comment by webron** [comment]
I think we should potentially change the structure of the extensions, so I'd wait with the name change proposal alone.

**Comment by jasonh-n-austin** [comment]
@webron I'd say the name change doesn't hurt, we've all agreed it should change anyways. If there are structural changes, we can address that separately (ready: easier to review PR).

👍

**Comment by webron** [comment]
:+1:

**Comment by fehguy** [comment]
👍

**Pull request merged**
