### PR TITLE
Add API Sprout to new mock server section

### PR DESCRIPTION
**Pull request by danielgtaylor**
Adds my new OpenAPI 3 mock server to the implementations list.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Just for consistency, is there a reason for having `CLI / Docker` as the `language` rather than `Go` ?

**Comment by danielgtaylor** [comment]
@MikeRalphson it wasn't clear to me whether the language should describe what a tool is written in or what language you as an end-user would use to interact with it. It might be interesting that it's written in Go, but it's really just a CLI tool anybody can easily install and run.

**Comment by danielgtaylor** [comment]
@MikeRalphson @darrelmiller any chance this could get merged in? Thanks :+1:

**Comment by danielgtaylor** [comment]
@MikeRalphson updated to show that it is written in Go now :smile:

**Comment by MikeRalphson** [comment]
Thanks for the contribution.

**Pull request merged**
