### PR TITLE
[new] scripts/update-schema-id.sh

### PR DESCRIPTION
**Pull request by TakahikoKawasaki**
This script updates the schema IDs in the following YAML files:

- schemas/v{major}.{minor}/schema.yaml
- schemas/v{major}.{minor}/schema-base.yaml

and generates the following JSON files from the updated YAML files:

- schemas/v{major}.{minor}/schema.json
- schemas/v{major}.{minor}/schema-base.json

### CODE REVIEW

**Review by ralfhandl — CHANGES_REQUESTED** [review]
Ran the script with `-v 3.1` and it worked fine.

Running with `-v 3.0` showed problems:
- schema.yaml was not updated
- schema-base.yaml was created empty
- schema-base.json was created with content `null`

**Comment by ralfhandl** [comment]
Hi @TakahikoKawasaki,

Thanks for providing the script. 

The script works fine for the v3.1 case with separate `schema` and `schema-base`, and fail for the v3.0 case where there is only `schema`.

Would you mind adding this distinction to the scripts?

Thanks in advance!

**Comment by TakahikoKawasaki** [comment]
@ralfhandl 
- Updated the script to support the version 3.0.
- Versions older than 3.0 are rejected on the assumption that maintenance of 2.x and older versions has stopped.

If it is necessary to support versions older than 3.0, please let me know.

**Comment by miqui** [comment]
@ralfhandl script so far looks good to me, but I'll let you run with it.

**Review by ralfhandl — APPROVED** [review]
Works for both v3.1 and v3.0

**Review by miqui — APPROVED** [review]

**Comment by karenetheridge** [comment]
I see you're using `ex` (which is a neutered form of `vim`) to do the substitutions -- I'm wondering why you made this choice, vs. the more usual choice of `sed` which provides access to a richer set of regular expressions?

**Comment by TakahikoKawasaki** [comment]
@karenetheridge Sorry, I did not know the `-i` option of `sed`. The `ex` command line can be replaced with `sed` if it is desired.

**Comment by lornajane** [comment]
I'm closing this pull request since it's no longer needed since the recent changes to the schema publishing process.

**Pull request closed without merging**
