### PR TITLE
Correct file extension on Alternative Schema Object

### PR DESCRIPTION
**Pull request by tedepstein**
Correcting the file extension from .adoc to .md so formatting displays correctly. This also fixes a broken link from the Alternative Schema Proposal.

### CODE REVIEW

**Comment by tedepstein** [comment]
@darrelmiller , @cmheazel , first instance of a pull request against a proposal. 

I'm requesting a review and expedited merge if it's OK. If it's not OK, please apply the label `P001` to associate this open PR with the proposal.

**Comment by cmheazel** [comment]
Thanks Ted.  PR #1913  includes these changes and a few more.  I suggest we pocket this one in favor of 1913.

**Comment by cmheazel** [comment]
Fixed along with a bundle of other issues in #1913.  Please merge #1913 so we can move on.

**Comment by cmheazel** [comment]
Superseded by #1993.  This PR is no longer needed.

**Comment by MikeRalphson** [comment]
#1993 was merged so this is no longer needed. Thanks both.

**Pull request closed without merging**
