### PR TITLE
Proposal: Add JWT audience in security scheme

### PR DESCRIPTION
**Pull request by emmanuelgautier**
As described in the [JWT RFC](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) and in the [OpenId Connect spec](https://openid.net/specs/openid-connect-core-1_0.html) for example, `audience` must be verified.

A client can request the audience during an OAuth 2.0 authorization flow, so having `audience` in the OpenAPI can be convenient. This audience documentation can also be used to add more documentation about the API security strategy and ensure the security is enforced.

### CODE REVIEW

**Comment by marzkud** [comment]
..!

**Review by robjtede — APPROVED** [review]

**Comment by darrelmiller** [comment]
This would be a good suggestion to trial as an `x-` to see the demand for this and the value it can bring.  It would also be good to bring this proposal along with other JWT related issues.

**Comment by handrews** [comment]
@emmanuelgautier since @darrelmiller suggested trying this out as an `x-` field first, I'm going to close this for now.  There is an issue already tracking this topic:

* #2239 

which mentions an `x-audience`, so if that's already being done and there's evidence that it's being used and working, please feel free to re-submit this PR and point to where it's being used.  We will also keep the issue open for consideration in 3.2 or some later 3.x with other JWT issues, as we have several that have been filed.  But it does not seem like there's enough consensus to add this to the spec _yet_.

**Comment by emmanuelgautier** [comment]
Thanks @darrelmiller and @handrews both for your review and sorry if I missed a submission process. This is my first contribution to the spec.

As suggested, more comments will be added then in the following issue about tokens here: https://github.com/OAI/OpenAPI-Specification/issues/2239.

**Comment by handrews** [comment]
@emmanuelgautier no worries about missing the process- we're coming out of a bit of a hibernation period and we're working on documenting our current processes through our [Contributor Guidance Project](https://github.com/orgs/OAI/projects/5).  So you didn't miss anything that you should have been able to figure out right now- we're working on it!

**Pull request closed without merging**
