### PR TITLE
Server Variable Object clarifications

### PR DESCRIPTION
**Pull request by webron**
Two clarifications:
- The `enum` of the Server Variable Object cannot be empty. This is different than the JSON Schema `enum`. The reason being that Server Variables must always have a value (see `default`), and an empty array suggests a 'no value' is acceptable.
- Since `enum` cannot be empty, and `default` is mandatory, if they both exist, the `default` value has to be one of the `enum` values (otherwise there's a conflict in logic).

If the PR is accepted, I'll submit the same change to 3.1.0.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
> If the PR is accepted, I'll submit the same change to 3.1.0.

I do have a script in the works which can create patches from one input file and try to apply them to another based on their last shared git history. It might be cleaner **not** to duplicate commits and to attempt to do them in a regularised manner.

**Comment by MikeRalphson** [comment]
Is adding a `MUST NOT` a bit strong for a patch release, even if it is a clarification of intent?

**Comment by webron** [comment]
Not in my opinion, but I'm biased 😀

**Comment by MikeRalphson** [comment]
My argument has always been that tooling implementations should be compatible no matter which patch release the authors read while implementing. If this change results in different `if` tests being required, and we would actually add non-backwards compatible changes to the schema for it (e.g. `minItems: 1`) then it's actually a breaking change, and would have to wait for v4. :man_facepalming:

**Comment by darrelmiller** [comment]
@webron  to fix this....

**Comment by webron** [comment]
@MikeRalphson please review again

**Comment by tedepstein** [comment]
@webron, @darrelmiller, @MikeRalphson, since you're on the subject, just a quick reminder that some of us out here don't understand server variables at all. Like, how are they supposed to work? 

Please see #1675.

**Pull request merged**
