### PR TITLE
Fix typo in 2.0.md

### PR DESCRIPTION
**Pull request by estliberitas**

### CODE REVIEW

**Comment by DavidBiesack** [comment]
I think "fka" was intentional, as "formerly known as" not "also known as". Might be better to spell it out thoogh.

**Comment by estliberitas** [comment]
@DavidBiesack ouch, sorry, did not know the origins :) Then, it's up to you guys.

**Comment by webron** [comment]
Yup, `fka` is the right term. Thanks for taking the time to submit it though.

**Comment by estliberitas** [comment]
@webron np ;)

**Pull request closed without merging**
