### PR TITLE
Add guidance on length of Path Item summary field

### PR DESCRIPTION
**Pull request by MikeRalphson**
As per Operation Object summary field

### CODE REVIEW

**Comment by webron** [comment]
We never really discussed if we want to add that similar guidance.

**Comment by darrelmiller** [comment]
LGTM

**Comment by DavidBiesack** [comment]
... but also needed for tag descriptions. I've seen people enter a paragraph, and it renders horribly in Swagger UI. (Unless, to be consistent, we add summary to tag objects, so descriptions can be longer...)

**Comment by RobDolinMS** [comment]
What do we want to do here?
a) Merge this
b) Don't merge this 
c) Consider updating to address the larger issue as mentioned by @DavidBiesack 
d) Something else?
/cc @MikeRalphson @webron @darrelmiller

**Comment by MikeRalphson** [comment]
Happy to rework to include option c. Or we can spin that off to a separate issue / PR to make sure it gets the eyeballs.

**Comment by webron** [comment]
I'm okay with adding this restriction but not in favor of the suggested tag-related changes.

**Comment by RobDolinMS** [comment]
@MikeRalphson Can you resolve the merge conflict?

**Comment by MikeRalphson** [comment]
@RobDolinMS done.

**Comment by RobDolinMS** [comment]
@webron and @darrelmiller would you please review this now one-line change?

**Comment by RobDolinMS** [comment]
* [ ] - TDC: Summary will not have any length restrictions
* [ ] - TDC: There should be tighter language explaining the difference between summary and description
@earth2marsh will open two PRs.  We can close this when those PRs are opened.

**Comment by earth2marsh** [comment]
This PR has been obsoleted by #1094 and #1095. Thanks for provoking the change!

**Pull request closed without merging**
