### PR TITLE
Remove examples folder [v3.0.4-dev branch]

### PR DESCRIPTION
**Pull request by Bellangelo**
Partially closes https://github.com/OAI/OpenAPI-Specification/issues/3854

We have moved in this https://github.com/OAI/learn.openapis.org/pull/102 the examples to the learn.openapis.org repo. So in this PR we are cleaning the main branch by removing the examples folder and making any related changes.

main: https://github.com/OAI/OpenAPI-Specification/pull/3913
v3.1.1-dev: https://github.com/OAI/OpenAPI-Specification/pull/3915
v3.2.0-dev: https://github.com/OAI/OpenAPI-Specification/pull/3916

### CODE REVIEW

**Review by mikekistler — APPROVED** [review]
Looks good! 👍

**Review by ralfhandl — COMMENTED** [review]
Please revert changes to the versions/*.md files

**Comment by ralfhandl** [comment]
Let's wait for publication of the patch versions and the subsequent cleanup of the dev branches.

**Review by miqui — APPROVED** [review]

**Comment by ralfhandl** [comment]
@Bellangelo Thanks for helping move the examples to https://learn.openapis.org/examples/

We have published 3.0.4 and will either lock this branch permanently or delete it, so closing this PR.

**Pull request closed without merging**
