### PR TITLE
Add missing type: object field in example schema

### PR DESCRIPTION
**Pull request by adriangb**
I think this is missing

### CODE REVIEW

**Comment by hkosova** [comment]
This was fixed in the 3.1.0 spec (PR #2361).

**Comment by adriangb** [comment]
I take it then that typo fixes like this don't get "backported"? If that's the case we can just close this PR

**Comment by hkosova** [comment]
> I take it then that typo fixes like this don't get "backported"?

Yes. Published versions of the spec are not amended.

**Comment by adriangb** [comment]
Gotcha. Closing this then.

**Pull request closed without merging**
