### PR TITLE
Correctly escape example operationRef URLs

### LINKED ISSUE #1677: URL-encoding for operationRef
I was under the impression that *operationRef* does not need URL-encoding. 

For example, in the following snippit taken directly from the [link object documentation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#link-object)...

```
links:
  UserRepositories:
    # returns array of '#/components/schemas/repository'
    operationRef: '#/paths/~12.0~1repositories~1{username}/get'
    parameters:
      username: $response.body#/username
```

... `{` and `}` are not encoded, i.e. replaced with `%7B` and `%7D`, like in the following:

```
links:
  UserRepositories:
    # returns array of '#/components/schemas/repository'
    operationRef: '#/paths/~12.0~1repositories~1%7Busername%7D/get'
    parameters:
      username: $response.body#/username
```

***

However, after talking to a developer of an OAS validator, I am doubtful... I was told that because *operationRef* is defined as a **reference** in the OAS, it needs URL-encoding.  

Here is the [link](https://github.com/Mermade/oas-kit/issues/85) to the discussion. The last two exchanges are most important to this topic. 

Could you clarify if *operationRef* needs URL-encoding?

### PR DESCRIPTION
**Pull request by handrews**
* Fixes #1677 

It's ugly, but that's URL-encoding for you.  If accepted, I will port this to 3.1.1 and 3.2.0.

### CODE REVIEW

**Review by ralfhandl — APPROVED** [review]

**Review by mikekistler — APPROVED** [review]
Looks ... ahh ... ugly ... but correct. 👍

**Comment by karenetheridge** [comment]
I'm not sure that this is needed now that we have the change from #3455 ?

**Comment by handrews** [comment]
@karenetheridge the schema is not normative and issue #1677 has TSC folks acknowledging that it needs URL-encoding.

So I guess we have to burn up Thursday meeting time on this after all?  This is what is so frustrating about trying to move forward.  We have such an immense backlog of minor things that they are all stepping on each other, and any attempt to resolve them runs into yet another contradiction or change in opinion.

**Comment by handrews** [comment]
The normative spec clearly states that `operationRef` is:

> A relative or absolute URI reference to an OAS operation.

Not a template.  So I think this change is correct and the schema change was wrong.  If we want it to be an unencoded template we'd need to change the spec language.

**Pull request merged**
