### PR TITLE
first stab at discoverability (#724)

### PR DESCRIPTION
**Pull request by dret**
not sure where this would go, feel free to move around. it's a bit hard to get a feel for the spec's structure with no available toc/outline view.

### CODE REVIEW

**Comment by DavidBiesack** [comment]
I recommend making the wording more like a guideline, less like a very loose suggestion. For example, rather than "Service providers may want to make an OpenAPI description discoverable", consider "Service providers wishing make an OpenAPI description discoverable may ...."  You can also be more concise by dropping the sentence "In such a scenario, it can help if there is a predictable way in which API description and documentation is made discoverbale from the API itself. " which is not necessary. Change "the following recommendations are made:" and "It is recommended that links" to just "Provide a link to the Open API Specification with the service-desc link relation", and so on.

**Comment by DavidBiesack** [comment]
The proposal should specify the JSON Home "hints"/"formats" should contains the supported media type,format, and versions (such as application/openapi+json;version=2.0 vs application/openapi+yaml;version=2.0 as described in #110 )

**Comment by dret** [comment]
On 2016-07-12 17:59, David Biesack wrote:
> The proposal should specify the JSON Home "hints"/"formats" should
> contains the supported media type,format, and versions (such as
> application/openapi+json;version=2.0 vs
> application/openapi+yaml;version=2.0 as described in #110
> <https://github.com/OAI/OpenAPI-Specification/issues/110> )

i am not sure that this needs to be recommended. media type hints are 
optional and if people feel like using them, that's ok. if they don't 
feel like using them, that's ok, too. why would you move away from that 
optional model and tell them that they should use hints?

**Comment by dret** [comment]
On 2016-07-12 17:56, David Biesack wrote:
> I recommend making the wording more like a guideline, less like a very
> loose suggestion. For example, rather than "Service providers may want
> to make an OpenAPI description discoverable", consider "Service
> providers wishing make an OpenAPI description discoverable may ...." You
> can also be more concise by dropping the sentence "In such a scenario,
> it can help if there is a predictable way in which API description and
> documentation is made discoverbale from the API itself. " which is not
> necessary. Change "the following recommendations are made:" and "It is
> recommended that links" to just "Provide a link to the Open API
> Specification with the service-desc link relation", and so on.

thanks for the feedback. i did a bit of rewriting at 
https://github.com/OAI/OpenAPI-Specification/pull/734/commits/0932f82b35b1196ca3d1cbf2e2f5c13c39d3d6a6 
and hope that this addresses your issues.

**Comment by DavidBiesack** [comment]
If we are recommending service-desc then I think it makes sense to recommend a consistent and complete representation of the link so that people have some guidance to follow . I did use the word "should". I'd rather not leave people guessing on what media type to use (and perhaps guessing wrong) or making them search somewhere to find out, or simply omit the type because the guidance does not mention it.

The rewrite looks much improved, thanks. Minor tweak: change "are using [the "service-desc" link relation type]" to "may use [the "service-desc" link relation type]"

**Comment by dret** [comment]
thanks for the feedback!

On 2016-07-14 15:16, David Biesack wrote:
> If we are recommending service-desc then I think it makes sense to
> recommend a consistent and complete representation of the link so that
> people have some guidance to follow . I did use the word "should". I'd
> rather not leave people guessing on what media type to use (and perhaps
> guessing wrong) or making them search somewhere to find out, or simply
> omit the type because the guidance does not mention it.

personally, i think it would be fine to omit the type, unless you have a 
specific reason to add such a hint to the link. i am curious if others 
have any opinion about mentioning/recommending/requiring a type hint.

> The rewrite looks much improved, thanks. Minor tweak: change "are using
> [the "service-desc" link relation type]" to "may use [the "service-desc"
> link relation type]"

https://github.com/OAI/OpenAPI-Specification/pull/734/commits/542f10d3b3566e8486aef2d83bb715bae009b188 
fixes this and uses the stronger "should" language you're suggesting above.

**Comment by dret** [comment]
anything else that's required here? thanks for the feedback so far!

**Comment by dret** [comment]
anything i can help to move this forward? it has been in the pipeline for a while. thanks!

**Comment by dret** [comment]
anything i can help to move this forward? it has been in the pipeline for a while. thanks!

**Comment by webron** [comment]
@dret - thanks for the submission. we're got a lot to cover and didn't get around to it this time, but it's on the queue for our next discussion.

**Comment by RobDolinMS** [comment]
@webron Would you please give this a look and comment on what should happen next?

**Comment by webron** [comment]
This is more of @darrelmiller's domain. If I understand it properly, I don't think it'll go into 3.0.0.. It won't make it into RC1 for sure.

**Pull request closed without merging**
