### PR TITLE
adds missing package lock for reproductible CI

### LINKED ISSUE #3556: this repository should contain a package-lock.json
Follow up to the conversation on today's call @handrews
Having only a package.json makes it so the CI installs might install different versions from what was originally installed and tested.
TODO:
- [x] remove exclusion from gitignore (if any)
- [x] `npm i` locally, and commit the package-lock.json
- [x] update all workflows to use `npm ci` instead of `npm i/install`
- [x] update the checkout in #3554 to also include that file.

I'm happy to take this on if we agree on the content. :)

### PR DESCRIPTION
**Pull request by baywet**
fixes #3556

### CODE REVIEW

**Comment by baywet** [comment]
Note: the schema test will fail until we merge to main since there currently isn't any package-lock.json on main

**Comment by baywet** [comment]
when you install locally, you'll get the same exact versions that were installed when this file was setup (or whenever a dependabot update was merged). It improves reproducibility

**Comment by baywet** [comment]
on the first pull after this gets merged however, you might have git complaining that you already have a package-lock.json if you've already ran `npm i`. Just delete it. That's a one time problem affecting people who installed before this PR.
People familiar with git and/or npm should be able to resolve that on their own without requiring assistance.

**Review by handrews — APPROVED** [review]
Looks good to me.  You'll need to make PRs copying the `schema-tests.yaml` workflow out to the v3.0.4-dev, v3.1.1-dev, and v3.2.0-dev (like PRs #3560, #3561, and #3562).

**Comment by handrews** [comment]
After some discussion last week, this sort of limited-impact change (most of our checks are failing right now anyway) can be merged with one approval, so I'm doing that.

**Pull request merged**
