### PR TITLE
Specification Extension instead of Vendor Extension

### PR DESCRIPTION
**Pull request by ralfhandl**
See #643

### CODE REVIEW

**Comment by ePaul** [comment]
Hmm, not sure if it is necessary to update the 2.0 spec with this.

**Comment by ralfhandl** [comment]
Not sure either. Finding other pull requests for the 2.0 spec and noticing changes in the public version at http://swagger.io/specification/ I updated both, so @fehguy et al. can decide which PRs to merge.

**Comment by fehguy** [comment]
we are not changing the 2.0 spec.

**Comment by ralfhandl** [comment]
Fine with me. What about the corresponding change #657 to the 3.0 spec?

**Pull request closed without merging**
