### PR TITLE
#2157: Update schema to validate refs in headers of encoding objects

### PR DESCRIPTION
**Pull request by alasdairhurst**
See https://github.com/OAI/OpenAPI-Specification/issues/2157

### CODE REVIEW

**Comment by alasdairhurst** [comment]
@webron thanks for approving. Are there any other approvals required or steps needed before this gets merged in? Just wondering what sort of time frame to expect.

**Comment by leonmende** [comment]
Usted es radiata!! No hace más que taparme!

**Comment by alasdairhurst** [comment]
no entiendo spansh. que es radiata?On 12 Dec 2020 06:50, leonmende <notifications@github.com> wrote:

Usted es radiata!! No hace más que taparme!

**Comment by leonmende** [comment]
No entiendo inglés!

**Comment by karenetheridge** [comment]
@leonmende https://translate.google.com/translate?hl=&sl=en&tl=es&u=https%3A%2F%2Fgithub.com%2FOAI%2FOpenAPI-Specification%2Fpull%2F2158

**Comment by leonmende** [comment]
Leon mendez

**Comment by leonmende** [comment]
Leon mendez patch

**Comment by leonmende** [comment]
Leon mendez patch

**Review by webron — APPROVED** [review]

**Review by MikeRalphson — APPROVED** [review]

**Pull request merged**
