### PR TITLE
Flow to flows

### LINKED ISSUE #967: Consider renaming oAuth Flows Object from 'flow' to 'flows'
This is probably a non-starter at this stage, but it is one of the rare examples in the specification of a singular noun being used to describe a collection. Changing this would draw attention to the fact this area of the specification has changed. See also #953 re: example/examples.

### PR DESCRIPTION
**Pull request by webron**
Resolves #967.

Also fixed the anchors in the OAuth Flow and OAuth Flows object. Used this PR because I was too lazy to open a separate one and it touched the same area. Shame on me.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Inline examples need updating.

**Comment by webron** [comment]
@MikeRalphson examples updated.

**Comment by RobDolinMS** [comment]
@darrelmiller When you have a chance, would you please give this a quick review.  This PR updates from "flow" to "flows" in a bunch of places.

**Comment by whitlockjc** [comment]
:shipit:

**Pull request merged**
