### PR TITLE
Proposal for Server Variable types

### PR DESCRIPTION
**Pull request by erunion**
To allow for the viability of tooling to validate server variables before composing a URL I'm proposing that a `type` property be added onto the [Server Variable Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#serverVariableObject) schema much in the same way parameters and schemas require one.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
As a result of #2604 the filename for this proposal should change to use a dated prefix. Please could you update this PR to match? You can use the original PR date. Apologies for the extra work.

**Comment by erunion** [comment]
@MikeRalphson 👍  All good now

**Comment by darrelmiller** [comment]
@erunion Thanks for submitting this.  Apologies for the long delay in responding.  Would you be available to present on this proposal in one of our Thursday TDC calls?

**Comment by darrelmiller** [comment]
@erunion We are closing this for the moment as it has been inactive for a while.  Please feel free to re-open if you want to follow up on this.

**Pull request closed without merging**
