### PR TITLE
Typo in discriminator example

### PR DESCRIPTION
**Pull request by ralfhandl**
Based on the proposed change to 3.1.1 in #3846 the 3.0.4 text seems to be wrong.

### CODE REVIEW

**Comment by handrews** [comment]
@ralfhandl there are several things that need backporting from PR #2618, this is only one of them- could you close this as it will be easier for me to backport if I don't have to split pieces out.  I've added #2618 to https://github.com/OAI/OpenAPI-Specification/issues/3626#issuecomment-2016888941 so we won't forget it.

**Review by handrews — CHANGES_REQUESTED** [review]
As noted in other comments, I'd prefer to port PRs as PRs and not individual lines.

**Comment by ralfhandl** [comment]
@handrews Don't find this typo explicitly mentioned in https://github.com/OAI/OpenAPI-Specification/issues/3626#issuecomment-2016888941, so why not just fix it by merging this trivial PR instead of risking it falling through the cracks?

Note: from my perspective 3.0.4 is the most relevant of the four specs we are currently working on.

**Comment by handrews** [comment]
This is now addressed on [this line](https://github.com/OAI/OpenAPI-Specification/pull/3880/files#diff-89e34372e8c32d43f8e3912385b9238745456d34646ebfbf91b3b0a263f9120dR2837) of the full merge resolution backport:
* #3880

**Pull request closed without merging**
