### PR TITLE
3.0.4: update from main

### PR DESCRIPTION
**Pull request by ralfhandl**
This merges current `main` into `v3.0.4-dev`, resolving the two merge conflicts in 
- .gitignore: taken from main
- validate-markdown.yaml: taken from v3.0.4-dev

### CODE REVIEW

**Review by mikekistler — APPROVED** [review]
Looks good. 👍 

I reviewed this by checking out the branch locally and then diffing with main.  Only 5 files are changed:
```text
>git diff main --name-only               
.github/workflows/validate-markdown.yaml
package-lock.json
package.json
scripts/format-markdown.sh
versions/3.0.4.md
```

Changes to versions/3.04.md are what we want. I checked the diffs of the other files and all look right.

**Comment by handrews** [comment]
Same question here- why are we doing this when we're about to merge in the other direction?

**Comment by handrews** [comment]
From a DM conversation, apparently this is how it's preferred to resolve conflicts, which seems messy to me but I won't object to it.

**Review by handrews — APPROVED** [review]
`3.0.4.md` was not changed so this looks good.

**Pull request merged**
