### PR TITLE
Adding path level tagging

### PR DESCRIPTION
**Pull request by ymohdriz**
Hi team,

Currently OAS supports tagging in API and operation level. This PR is to add tagging in path level also.
Related feature request related to this:
OAI#1367

Please review the PR and merge the same.

Thanks,
Mohammed

### CODE REVIEW

**Comment by darrelmiller** [comment]
Hey @ymohdriz Thanks for the PR.  This is definitely an interesting addition that has a low impact on the spec.  However, we do have to consider the impact on tooling.  We would need to get feedback from folks who are producing documentation based on OpenAPI as to whether they have user requests for these features and whether they are prepared to do the work to incorporate this capability.

Also, this kind of change cannot go into a patch release, it would need to go into a 3.1 branch which I don't believe we have yet created because we are still working on what features will go into 3.1.

We will definitely consider this for inclusion and the more feedback we can get from tooling people on this, the easier it will be to make the call.

**Comment by ymohdriz** [comment]
Hi @darrelmiller,

Thanks for the detailed response.
I would like to contribute to this project. But new PRs may turn into new features. 
Can you please suggest some areas to work on?

Thanks,
Mohammed

**Comment by emreakca** [comment]
Hey @darrelmiller,

What's the state? Are subtags considered to be a feature, because it would be great!
If it's possible, a push would be very helpful!

**Comment by MikeRalphson** [comment]
This PR cannot be accepted as-is, because a) it is targeted at v2.0 of the specification, which is published and will not change, b) it only updates the schema file, which is not the source-of-truth of the specification (the markdown documents are), c) as @darrelmiller says, this change (if accepted) would need to go into a minor release, such as v3.1.0

@emreakca if you need sub-tag grouping / a hierarchy of tags, it would probably be worth commenting on #1367 or #1507 as appropriate.

**Comment by MikeRalphson** [comment]
Closing, for the reasons given in https://github.com/OAI/OpenAPI-Specification/pull/1509#issuecomment-402967954

**Pull request closed without merging**
