### PR TITLE
Add OpenAPI Generator to IMPLEMENTATIONS.md

### PR DESCRIPTION
**Pull request by wing328**
Add OpenAPI Generator, which supports both OpenAPI spec v2 and v3.

### CODE REVIEW

**Comment by earth2marsh** [comment]
This definitely qualifies as a tool that leverages the spec. My concern is that unlike other implementations in this list, the GitHub organization `openapitools` is a name that could be confused as an official project. I'd prefer a note added to this entry like, "Note: the openapitools organization is an independent, community project not provided by the OpenAPI Initiative." (or similar)

**Comment by wing328** [comment]
@earth2marsh thanks for the feedback. I've updated the PR to include the following

> Both "OpenAPI Tools" (https://OpenAPITools.org - the parent organization of OpenAPI Generator) and "OpenAPI Generator" are not affiliated with OpenAPI Initiative (OAI)

@ladd @chatelao thanks for reviewing the change

**Comment by ackintosh** [comment]
> This branch has conflicts that must be resolved

👀

**Comment by tnielens** [comment]
I just read through the code generation tool list today and was surprised not to find OpenAPITools' `openapi-codegen`, nor `swagger-codegen` in the list. I have the impression those tools have played an important role in the success of the OpenApi specs.

**Comment by MikeRalphson** [comment]
Thanks for the PR. We are now in the process of moving from `IMPLEMENTATIONS.md` to https://tools.openapis.org - the current implementations list will be removed and a note redirecting readers to the new site added. Instructions on listing your projects are contained in https://github.com/OAI/Tooling#how-can-you-help

**Pull request closed without merging**
