### PR TITLE
Add Connexion Python framework

### PR DESCRIPTION
**Pull request by m-aciek**
To server implementations.

Related to: https://github.com/zalando/connexion/issues/1270.

### CODE REVIEW

**Review by ioggstream — APPROVED** [review]
LGTM

**Comment by RobbeSneyders** [comment]
Connexion maintainer here. Is there anything we can do to get this merged?

**Comment by nfroidure** [comment]
I was about to do a PR for [Whook](https://github.com/nfroidure/whook) but is is still relevant since there is a bunch of PRs like that one waiting for a merge?

**Comment by MikeRalphson** [comment]
We're looking to replace the static `IMPLEMENTATIONS.md` file with a more comprehensive tooling list which is easier to maintain - hence the hold on merging these PRs for now.

**Review by darrelmiller — APPROVED** [review]

**Pull request merged**
