### PR TITLE
Ensure that array always have "items" attribute.

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Implement based on comments from #404

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
It passing all JS test, but fails somewhere inside Scala tests.
I don't have any Scala knowledge to fix it :(

**Comment by webron** [comment]
@IvanGoncharov - thanks, I'll review it and the tests. If the change is good, I'll work on the tests. It'll take a while though.

**Comment by IvanGoncharov** [comment]
I review Scala tests and they are simple.
Is there are any reasons why they implemented in Scala?
They could be easily replaced with 30-40 lines in JS.
It could be easier than fix bugs in abandoned library:
https://github.com/fge/json-schema-validator#this-project-is-looking-for-a-new-maintainer

**Comment by webron** [comment]
Knowing the library's author, I also know the project is not abandoned.

**Comment by IvanGoncharov** [comment]
So how about moving these test into https://github.com/swagger-api/swagger-spec/blob/master/test/validate.js ?
I can create separate PR.

**Comment by webron** [comment]
Sure, but unfortunately it would take me a while to review it.

**Comment by IvanGoncharov** [comment]
I understand.
I will create separate PR and link it to this.

**Comment by webron** [comment]
Thanks!

**Comment by webron** [comment]
@IvanGoncharov - any update on this?

**Comment by IvanGoncharov** [comment]
@webron Just started migrated tests.
Problem that for some reason I can't run even vanilla tests on my machine :(
I will create separate issue with WIP status.

**Comment by webron** [comment]
@IvanGoncharov - closing this for now. Really trying to minimize changes to things related to 2.0.

**Pull request closed without merging**
