### PR TITLE
json-schema.org, commonmark.org and yaml.org now support https

### PR DESCRIPTION
**Pull request by MikeRalphson**
Revisits #1422 now that json-schema.org and commonmark.org support https. ~~This just leaves yaml.org :sob:~~

### CODE REVIEW

**Comment by ingydotnet** [comment]
https://yaml.org :P

**Comment by MikeRalphson** [comment]
Firefox complains yaml.org has https issues.

**Comment by MikeRalphson** [comment]
> Firefox complains yaml.org has https issues.

Firefox 64.0 no longer complains as of this date. Will update PR.

**Comment by MikeRalphson** [comment]
https://yaml.org is fine, but https://www.yaml.org is misconfigured. Removed `www.` from links.

**Comment by ingydotnet** [comment]
@clarkevans can you take a look at the DNS for www.yaml.org?

http://www.yaml.org redirects to https://yaml.org which works fine.

However https://www.yaml.org is not working fine.

**Pull request merged**
