### PR TITLE
gh-pages: view link and download link for latest JSON schemas

### PR DESCRIPTION
**Pull request by ralfhandl**
- HTML wrappers for "schema" and "schema-base" for nice rendering of latest schema version
- download links for all published schema versions

image

Preview: https://ralfhandl.github.io/OpenAPI-Specification/

### CODE REVIEW

**Review by mikekistler — DISMISSED** [review]
Looks good. 👍 

Strange highlighting in the "latest" files -- I'm taking that to be a GitHub anomaly.

**Review by mikekistler — DISMISSED** [review]
Reapproving.

**Comment by handrews** [comment]
@ralfhandl now I'm noticing that these are called "latest", but really we want people to take specific dated versions of the schema.  It's not good to have your validation rules change under you without notice.  Or am I misunderstanding what "latest" means here?

**Comment by ralfhandl** [comment]
@handrews How about listing all schema versions for download, and only viewing the latest in an HTML wrapper:

image

Live preview:
* https://ralfhandl.github.io/OpenAPI-Specification/

**Review by handrews — APPROVED** [review]
This is an improvement over what we have!

**Review by lornajane — APPROVED** [review]

**Review by miqui — APPROVED** [review]

**Review by handrews — APPROVED** [review]

**Pull request merged**
