### PR TITLE
Changed anchor tags from camelCase to snake-case, Fix for issue #1726

### PR DESCRIPTION
**Pull request by MariusLerf**
Fix for #1726

### CODE REVIEW

**Comment by ramsey** [comment]
I guess the big question is: will GitHub fix the issue, or does this need to be merged to fix the issue? This is a problem on every repository that linked to anchors, so the OAI docs repo is not the only one affected.

**Comment by cebe** [comment]
According to Github support this was an unintentionally made breaking change and they are working on a solution. Given the fact that it is working for me right now, I assume they are rolling out the fix to a limited set of accounts or networks before applying it for all.

**Comment by cebe** [comment]
Btw: While this PR fixes it for master, it breaks external links to the spec, that refer to specific headlines and it does not fix it for links that point to a tag instead of master. So I'd prefer to wait for github fixing it instead of merging this. For future stability it might be wise to not rely on github for hosting it but to put it on the website instead.

**Comment by MikeRalphson** [comment]
Thanks @cebe 

>  For future stability it might be wise to not rely on github for hosting it but to put it on the website instead.

This is under development -- see #1564, though the markdown version will remain the source-of-truth.

**Pull request closed without merging**
