### PR TITLE
Fix typo of extra closing brace

### PR DESCRIPTION
**Pull request by adamaltman**
Noticed while re-reading the spec.

### CODE REVIEW

**Review by darrelmiller — APPROVED** [review]

**Comment by handrews** [comment]
Does this need to get re-targeted to `versions/3.1.1.md` on the `v3.1.1-dev` branch?

**Comment by darrelmiller** [comment]
@handrews  Yes it does.  I missed that when I approved.

**Comment by lornajane** [comment]
@adamaltman could you update to target the version-specific files/branches please?

**Comment by handrews** [comment]
It looks like this [already got fixed in 3.1.1.md](https://github.com/OAI/OpenAPI-Specification/commit/b31554ad99939f1517521c30cbfbd2382aee518e#diff-b92507e7acda65ae00a02236c555cefc68b6fca4661077b84c2fb9ab150e5e17L198), and we forgot to close out this PR when that happened.  Closing now- thanks for bringing it to our attention!

**Pull request closed without merging**
