### PR TITLE
Added required fields

### LINKED ISSUE #962: 3.0.0-rc0 ServerObject has no required fields?
The `url` field for [ServerObject](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#serverObject) isn't explicitly marked as required? Shouldn't it be? Presumably all servers have URL's and the `variables` field is dependant on it being defined. You wouldn't (couldn't) define `variables` but not `url`.

### PR DESCRIPTION
**Pull request by webron**
Resolves #962, #963.

Added required `url` for Server, and `content` for Request Body.

### CODE REVIEW

**Comment by RobDolinMS** [comment]
@webron Would you please elaborate on why requestBodyContent is required ?

(I didn't see a clear reason for this in #963)

**Comment by whitlockjc** [comment]
I'm with @RobDolinMS, I'd like to understand why `requestBodyContent` is required.

**Comment by webron** [comment]
The Request Body Object currently has no required fields. That means you can specify a request body without specifying anything. That has no semantic meaning. If you define a request body, you should define what it represents. Even if it's any value, it should be specified, meaning, you have to have `content` in it.

**Comment by whitlockjc** [comment]
I thought all `content` properties were optional, which is why this one being required surprised me.  I'll go back through the document to see if `content` being required makes sense.

**Comment by whitlockjc** [comment]
:shipit:

After talking with @webron about this offline, it makes sense to me now.

**Pull request merged**
