### PR TITLE
Update 3.0.4.md to fix broken links

### PR DESCRIPTION
**Pull request by mojorero**
The original links got 404 errors.

### CODE REVIEW

**Review by rafalkrupinski — APPROVED** [review]

**Comment by darrelmiller** [comment]
Thank you for bringing this to our attention. We will ensure this is fixed when we release 3.0.4

**Comment by handrews** [comment]
@mojorero and/or @OAI/tsc , could someone port this to `versions/3.0.4.md` on branch `v3.0.4-dev`?

**Comment by darrelmiller** [comment]
Hmm, I changed the base but that didn't have the desired effort.  I can recreate the change to make the fix if the change hasn't been updated in some other PR.

**Comment by handrews** [comment]
The link fixes have been consolidated for all versions in PR #3408 (and follow-up PRs as noted in its description), so I am closing all other link fix PRs in favor of that one.

**Pull request closed without merging**
