### PR TITLE
feat: rendering of the Arazzo Specification

### PR DESCRIPTION
**Pull request by frankkilcommins**
Adding the rendering of the Arazzo Specification.

fixes the following Arazzo Specification issues:
- https://github.com/OAI/Arazzo-Specification/issues/42
- https://github.com/OAI/Arazzo-Specification/issues/49

refs:
- https://github.com/OAI/Arazzo-Specification/issues/117

### CODE REVIEW

**Comment by ralfhandl** [comment]
Looks convincing 😄

**Comment by handrews** [comment]
@frankkilcommins why is respect-arazzo.js formatted as a single line?  respec-oai.js is not, and single-line JS files are not fun for diffs (or readability at all).

**Comment by frankkilcommins** [comment]
> @frankkilcommins why is respect-arazzo.js formatted as a single line? respec-oai.js is not, and single-line JS files are not fun for diffs (or readability at all).

@handrews strange.....both look the same for me (very long single line at the start). The only change in the file was replacing a hardcoding "What is the OpenAPI Specification" with "What is the Arazzo Specification" as I don't have time right now to fix all the things.

**Comment by ralfhandl** [comment]
> respec-oai.js is not

It actually is if you look at the raw file and not at the formatted version the Github UI renders: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/gh-pages/js/respec-oai.js

**Comment by handrews** [comment]
@frankkilcommins Someone explain that the GitHub view I was using of the other file formatted it, so yeah, you're fine with the one-liner as far as I'm concerned

**Review by handrews — APPROVED** [review]

**Review by lornajane — APPROVED** [review]
Yes! Go Arazzo :)

**Review by darrelmiller — APPROVED** [review]

**Pull request merged**
