### PR TITLE
Add "latest" URLs for downloading schemas

### PR DESCRIPTION
**Pull request by jdesrosiers**
In the last schema update, it came up a couple times that people would like to be able to use `https://spec.openapis.org/oas/3.1/schema` (without a release date) to access the latest version of the schema. That makes perfect sense. Unfortunately, GitHub Pages makes it difficult to serve that exact URL. So, instead I'm proposing "latest" URLs.

* https://spec.openapis.org/oas/3.1/schema/latest
* https://spec.openapis.org/oas/3.1/schema-base/latest
* https://spec.openapis.org/oas/3.0/schema/latest

### CODE REVIEW

**Review by darrelmiller — APPROVED** [review]

**Comment by karenetheridge** [comment]
Those URLs don't resolve. What is needed to get them working on GitHub Pages?

**Comment by karenetheridge** [comment]
It would also be helpful to link to these from a documentation page somewhere.

**Comment by jdesrosiers** [comment]
Not sure why that didn't work. I'll look into it.

**Comment by jdesrosiers** [comment]
I'm stumped. It works on my local build. There's every indication that this solution is something that Github Pages supports out of the box. There are multiple examples including the JSON Schema Github Pages site that show that it should work.

Is there a plugin or something being used that might be interfere with with this feature?

**Comment by seriousme** [comment]
My automated test noticed an error.
The symlink of 3.0 contains an typo. 

The 3.0 schema folder contains:
```bash
2021-09-28
latest -> 2012-09-28
```
2012 should be 2021 ;-)

Kind regards,
Hans

**Comment by jdesrosiers** [comment]
Thanks, @seriousme. I looked for that exact typo and I still missed it :man_facepalming:

**Comment by seriousme** [comment]
Issue still seems to be there:
https://github.com/OAI/OpenAPI-Specification/blob/18717adbff3148874e87aaa4606c8836624c4b1f/oas/3.0/schema/latest#L1

Kind regards,
Hans

**Pull request merged**
