### PR TITLE
- adds a base64url format description

### PR DESCRIPTION
**Pull request by baywet**
related #3167

### CODE REVIEW

**Comment by handrews** [comment]
@baywet I think you need to update this to remove the deprecated version info.

I'm also wondering if, now that we have definitively settled on `byte` rather than `base64`, if it makes sense to align with RFC 4648 terminology for this, or call it `byteUrl` or something.  Neither feels very satisfactory to me.

**Comment by baywet** [comment]
Can you expand on why do you think we should remove the deprecated aspect please? I might have missed part of the conversation here.

If it were only up to me, byte would be base64 and base64url would be base64url. byte only being an alias to byte64 for compatibility reasons. Those different names are simply adding confusion IMHO.

**Comment by handrews** [comment]
Edit to my previous comment: formats are kebab-case so `byte-url`, not `byteUrl`

Re: `deprecated_note` — see https://github.com/OAI/OpenAPI-Specification/pull/3167#issuecomment-1456845756

In #3174 I suggested having a `base64` alias for `byte` but we discussed it in the last call and decided not to do that (as seen in #3182).  So we're stuck with `byte`.

**Comment by baywet** [comment]
@handrews so are we good with this PR as is or do you suggest we make other changes?

**Comment by handrews** [comment]
I'm still feeling meh about whether to use `base64url` for compatibility with OAS 3.1 vs `byte-url` for compatibility with OAS 3.0, the actual targeted version here.  As much as I dislike `byte`, it's what we're stuck with and this is a URL-safe version of it.  Although I suspect that very few tools will implement support for this so I'm not sure how much it matters.

@MikeRalphson, @darrelmiller, anyone else - any preference for `base64url` vs `byte-url` in the context of OpenAPI 3.0?

**Comment by MikeRalphson** [comment]
+1 for base64url, let's not be held back by our past missteps.

**Comment by handrews** [comment]
@MikeRalphson thanks - in that case this looks good to go.

**Review by handrews — APPROVED** [review]

**Review by MikeRalphson — APPROVED** [review]
LGTM

**Pull request merged**
