### PR TITLE
Add an initial draft for a proposal for an 'archetype' field for paths.

### PR DESCRIPTION
**Pull request by myronww**
This is an initial draft for a proposal for adding an 'archetype' field to the specification for paths.  I am adding a PR for this initial draft so I can get feedback on the proposal.

### CODE REVIEW

**Comment by karenetheridge** [comment]
There's too many issues and PRs all discussing this proposal; where is the canonical location for that? And can the other locations be closed?

**Comment by myronww** [comment]
> There's too many issues and PRs all discussing this proposal; where is the canonical location for that? And can the other locations be closed?

So, can you refer me to some of the other issues and proposals, or provide some relevant search terms.   Can you provide a list of specific actions items that your requesting in order to make progress.

**Comment by myronww** [comment]
Here are links to other issues open on this that are related.  Here is the open issue that I opened for this.

https://github.com/OAI/OpenAPI-Specification/issues/3372

Here are some past issues that look to be related.

https://github.com/OAI/OpenAPI-Specification/issues/577
https://github.com/OAI/OpenAPI-Specification/issues/576

**Comment by myronww** [comment]
> There's too many issues and PRs all discussing this proposal; where is the canonical location for that? And can the other locations be closed?

If you know of any other issues that are related that i should like or any search terms i could use to find related issues, that would be great.

**Comment by handrews** [comment]
Filed #3257 to revive and clarify our proposals process.  Once we figure it out, we'll resolve this PR accordingly.

**Pull request closed without merging**
