### PR TITLE
Correct type field description in items object

### PR DESCRIPTION
**Pull request by samskiter**

### CODE REVIEW

**Comment by webron** [comment]
I'm afraid `"object"` is not allowed there.

**Comment by samskiter** [comment]
Are you sure? An array of objects seems a pretty basic thing to support and is supported as far as I could tell from the parsers/generators I'd used.
In fact there are arrays with refs to items with type set to object in the swagger example on the editor http://editor.swagger.io/#/

**Comment by webron** [comment]
The `Items Object` is the one used by non-Schema Object arrays, where objects are not allowed. For example, all non-body parameters. Check the spec carefully as to what points to the `Items Object`.

**Comment by ePaul** [comment]
#654 will actually make a schema allowed for all parameters in 3.0, which makes this section go away.

I guess this change for the 2.0 version can be closed without merging.

**Comment by webron** [comment]
This can be closed now as it's for 2.0.

**Pull request closed without merging**
