### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by sergej2705**

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Sorry, my bad, the PR needs to update ` versions/3.0.3.md` too.

**Comment by sergej2705** [comment]
already done by https://github.com/OAI/OpenAPI-Specification/pull/1785/commits/7837eb4e1834439ba815a852d1be8b8ae065afe5

**Comment by MikeRalphson** [comment]
Thanks, update to `3.0.2` should be a nop **if this PR is squashed**.

**Comment by MikeRalphson** [comment]
@sergej2705 could you remove the commits that reference `3.0.2.md` completely? Patch level changes should only affect one (upcoming) release version.

**Comment by sergej2705** [comment]
done

**Pull request merged**
