### PR TITLE
security; widen use of scopes array to other securityScheme types

### PR DESCRIPTION
**Pull request by MikeRalphson**
Split off from #1764 as discussed. In summary, I believe the outstanding issue is to find a non-contentious term possibly in preference to `scopes` or `roles` and to check this makes sense for all securityScheme types, including `http`'s subtypes.

### CODE REVIEW

**Comment by ioggstream** [comment]
imho this change should include/reference some spec examples.

**Comment by darrelmiller** [comment]
@darrelmiller Review naming of scopes vs roles

**Comment by darrelmiller** [comment]
This PR allows the use of scopes for non OAuth2 security schemes.  It does not provide a way to describe the set of valid scopes for those scenarios.  We do believe that it would be valuable to have a place to define the allowed scopes but we need to spend some more time discussing how this can be incorporated into the SecurityScheme object.  We will do this in the rc1 timeframe.

**Comment by ioggstream** [comment]
>  we need to spend some more time discussing how this can be incorporated into the SecurityScheme object. We will do this in the rc1 timeframe.

WDYT to add some example to this PR as a comment?

**Comment by glroman** [comment]
As mentioned in #1106 and #1903, it would be really useful to support the ORing of scopes.  For example:

  /pet:
    post:
      security:
        - oauthScopes: [read, write] | [admin]

Will this be in the PR?  Thanks.

**Comment by MikeRalphson** [comment]
@glroman can you not do:

```yaml
  /pet:
    post:
      security:
        - oauthScopes: [read, write]
        - oauthScopes: [admin]
```

> Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information.

This is ANDing. Here you can't have two references to `oauthScopes` because that would be a duplicate YAML/JSON key, but you could merge the scopes arrays.

> When a list of Security Requirement Objects is defined on the OpenAPI Object or Operation Object, only one of the Security Requirement Objects in the list needs to be satisfied to authorize the request.

This is ORing. Here you **can** have multiple references to `oauthScopes` because they are in separate elements of the `security` array.

**Comment by glroman** [comment]
When I connect with a client that has "admin", this works:

    /pet:  # Scenario 1
       post:
         security:
           - oauthScopes: [read, write]
           - oauthScopes: [admin]

but this doesn't:

    /pet:  # Scenario 2
       post:
         security:
           - oauthScopes: [admin]
           - oauthScopes: [read, write]

I get:

    {
      "detail": "Provided token doesn't have the required scope",
      "status": 403,
      "title": "Forbidden",
      "type": "about:blank"
    }


Is this expected behavior?  My env:

    python                  3.7.1
    connexion               2.6.0
    openapi-spec-validator  0.2.8

**Comment by MikeRalphson** [comment]
I think that may be an issue with `connexion` then.

**Comment by darrelmiller** [comment]
@ioggstream  We have the opportunity to add examples in the examples not included in the spec.  I don't think we need to include an example in the specification because I do not think there is widespread usage of scopes in non-OAuth2 scenarios.

@MikeRalphson  I have come to terms with the use of the term "role".  I don't feel the need to change it here.

Defining scopes/roles at the security scheme level is not going to make it into 3.1.

**Pull request merged**
