### PR TITLE
[File Structure] Clarify name convention is optional

### PR DESCRIPTION
**Pull request by RobDolinMS**
Liz Lynch found wording confusing.  

Use "MAY" to indicate this is optional.

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by webron** [comment]
I'm leaning towards SHOULD rather than MAY.

**Comment by RobDolinMS** [comment]
I'm hesitant on "SHOULD" since it sometimes is used to suggest an action should be done unless there is a good reason not to.  

Other opinions?

**Comment by webron** [comment]
I see it as our recommendation to do that. We don't really dive into discovery much, and as a standard way I think we need to encourage people to do that.

Using MAY feels like with might as well not add that suggestion at all (especially if you read the full sentence). Saying that by convention something MAY be named something to me sounds odd.

**Comment by ePaul** [comment]
If we recommend something like this, we should have a reason.
What is the reason for having a conventional name of a API specification file?

* Allowing only one such file per directory in a file system? (Why would you want to prescribe something like this?)
* Having it reachable in the root of the API it describes? (Then it is not so much about the file name, but about a well known URL path component.)
* any other reason?

**Comment by RobDolinMS** [comment]
Per TDC discussion, let's use "RECOMMENDED"

**Comment by ePaul** [comment]
I still would like to know the reason for recommending a specific name.

**Comment by RobDolinMS** [comment]
I've updated this PR per TDC discussion to use "RECOMMENDED" /cc @ePaul 

@webron If this looks good, please merge.

**Comment by webron** [comment]
@ePaul without diving into details and complicating things - for better or worse, this is how the discovery of the spec has worked so far, and we're too late in the game to change it for 3.0. We recommend doing so, but it's been the common practice until now and people should be familiar with it. It may not be a _technical_ reason, but a reason still. We can open discussion for changes to that in the next major version (and I believe there's a ticket).

**Pull request merged**
