### PR TITLE
Add a missing ].

### PR DESCRIPTION
**Pull request by timburks**
Fix an ill-formed type for the Link Object parameters field.

### CODE REVIEW

**Comment by earth2marsh** [comment]
LGTM

**Comment by whitlockjc** [comment]
:shipit:

**Comment by RobDolinMS** [comment]
@darrelmiller to resolve merge conflict

**Comment by darrelmiller** [comment]
It looks like this is a PR from a branch in Tim's repo so I don't think I can edit it.  I don't think creating a PR to Tim's PR for a 2 character change is such a wise idea :-)  Handing this issue back off to /cc @timburks

**Comment by ePaul** [comment]
@darrelmiller If you have write access to master, you can simply merge master and the PR branch locally and push the result directly to master (this PR will automatically be marked as merged). (Not sure if the policy/settings for this repository allow this, though.)

**Comment by timburks** [comment]
I'm happy to make a change if needed but haven't figured out what the necessary change would be.

**Comment by ePaul** [comment]
@timburks I think this is just to merge this repository's OpenApi.next into your branch and resolve the conflicts.

**Comment by RobDolinMS** [comment]
Since these changes were included in another PR, we can close.

**Pull request closed without merging**
