### PR TITLE
Release v3.1.1

### PR DESCRIPTION
**Pull request by ralfhandl**
This PR will merge `v3.1.1-dev` into `main`.

Still to do:
- [x] Write Release Notes: @lornajane, @handrews
  - #4095
- [x] Merge last-minute PRs 
  - #4079
  - #4085
  - #4088
  - #4091
  - #4110 
  - 3.1.1 port of #4100

### CODE REVIEW

**Review by darrelmiller — DISMISSED** [review]

**Comment by ross-paypay** [comment]
Thanks to everyone for the work on this!
Really looking forward to Generic Data Structures getting added to the spec.

Is there any ETA on when this will get merged?

**Comment by ralfhandl** [comment]
@ross-paypay Thanks!

We decided to add #4100 to 3.0.4 and its port to 3.1.1, and it may take us a few weeks to polish that change.

**Comment by baywet** [comment]
I might have missed something here. But wanted to make sure this wasn't forgotten before the release goes out. This release still contains plenty of links to json schema draft 00 from ben hutton. I thought we meant to correct them to draft 12?

**Comment by handrews** [comment]
@baywet See issue #3934 and #4127 – this isn't something we change in a patch release (same for superseded RFCs, see issue #3800 )

**Comment by handrews** [comment]
@baywet 

> I thought we meant to correct them to draft 12?

That draft is draft 2020-12.  The IETF draft numbers and the metaschema dates are not related.

**Comment by handrews** [comment]
@ross-paypay 

> Really looking forward to Generic Data Structures getting added to the spec.
> 
> Is there any ETA on when this will get merged?

As this is a proper patch release, all of the "changes" here actually also apply to 3.1.0.  We're just making them more clear.  The generic data structures thing is something some JSON Schema folks figured out you can do with `$dynamicRef`, it's not even something we came up with.  So feel free to lobby your tooling vendor to support them for 3.1 in general, not just 3.1.1.

As for merging, I'm hoping we'll put 3.0.4 and 3.1.1 in the final week-long voting period in the TDC call today.

**Review by darrelmiller — DISMISSED** [review]

**Review by miqui — APPROVED** [review]

**Comment by miqui** [comment]
Looks good to me (approved)

**Review by lornajane — APPROVED** [review]

**Review by earth2marsh — DISMISSED** [review]
Looks great--thanks for all the hard work!

**Review by earth2marsh — DISMISSED** [review]

**Review by mikekistler — APPROVED** [review]
Looks good. 👍 

I approve this for release.

**Review by lornajane — APPROVED** [review]

**Review by Aidan420nan — COMMENTED** [review]
Jjjj

**Review by Andibeethoven — COMMENTED** [review]
Why can I not help edit on GitHub?

**Review by MrG9090 — APPROVED** [review]

**Review by alexkemagoodluck8-commits — APPROVED** [review]

**Review by alexkemagoodluck8-commits — APPROVED** [review]

**Pull request merged**
