### PR TITLE
actions: reinstate validation of schemas and examples, fixes #1739

### LINKED ISSUE #1739: Reinstate validation of JSON Schemas (and examples) in build process
This issue is a place-holder to ensure this action isn't forgotten.

If we want to validate OAS instances beyond compliance with our JSON schemas, we would need to make a choice on which validator(s) to use - this would not be an endorsement.

Can occur after the resolution of #1270 / #1236

### PR DESCRIPTION
**Pull request by MikeRalphson**
As promised, following the merging of #1270 / #1897

**Note**: *items related to publishing an npm package containing the schemas will be moved to a new issue*.

This PR now reinstates the validation of examples and schemas using GitHub Actions.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
> >   We still need to work on a few details.

> @MikeRalphson Is there a list of these details / anyway we can help out? Even a pre-release of current state would be great, we're blocked by using the existing swagger-schema-official package by our legal team and getting out an update with valid license would allow us to continue.

@kylef for visibility I've copied your comment here from #1730 as that PR is merged and added the TODO items as I see them now to the initial comment.

**Comment by kylef** [comment]
Thanks @MikeRalphson.

I'd add one more point to the TODO tasks above, once released we should signal in NPM that the existing [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) package is deprecated, this can be done with the [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) command.

I can provide some input on some of the questions above:

> determine if Apache-2.0 LICENSE file also needs including in generated packages

I can confirm the `LICENSE` file in root is picked up by NPM, this can be verified via `npm pack` which creates the tarball of the package and lists files included:

```
npm notice 📦  oas-schemas@2.0.0
npm notice === Tarball Contents ===
npm notice 687B   package.json
npm notice 11.3kB LICENSE
npm notice 5.9kB  README.md
npm notice 4.4kB  schemas/jsonSchema/draft-04/metaschema.json
npm notice 1.9kB  schemas/v1.2/apiDeclaration.json
npm notice 1.8kB  schemas/v1.2/authorizationObject.json
npm notice 4.6kB  schemas/v1.2/dataType.json
npm notice 2.6kB  schemas/v1.2/dataTypeBase.json
npm notice 661B   schemas/v1.2/infoObject.json
npm notice 1.0kB  schemas/v1.2/modelsObject.json
npm notice 2.0kB  schemas/v1.2/oauth2GrantType.json
npm notice 2.4kB  schemas/v1.2/operationObject.json
npm notice 1.3kB  schemas/v1.2/parameterObject.json
npm notice 325B   schemas/v1.2/README.md
npm notice 592B   schemas/v1.2/resourceListing.json
npm notice 385B   schemas/v1.2/resourceObject.json
npm notice 248B   schemas/v2.0/README.md
npm notice 40.2kB schemas/v2.0/schema.json
npm notice 890B   schemas/v3.0/README.md
npm notice 35.5kB schemas/v3.0/schema.json
npm notice 22.1kB schemas/v3.0/schema.yaml
npm notice === Tarball Details ===
npm notice name:          oas-schemas
npm notice version:       2.0.0
npm notice filename:      oas-schemas-2.0.0.tgz
```

> which npm org to publish packages to (new/existing)?

For consistency with GitHub, perhaps creating an `oai` NPM org would make sense.

The prior specifictions package was released under the [`swagger` user on NPM](https://www.npmjs.com/~swagger) which also contains swagger-editor and other packages.

> who will have publish rights

Since there is a TODO for `setup automated publishing via Travis deploy`, this will be anyone who has GitHub push/write acces?

**Comment by darrelmiller** [comment]
Action: @MikeRalphson to update package versions.

**Comment by handrews** [comment]
This PR is now out of date and does not fit with newer schema test workflows or the version requirements of our node environment, and the original submitter is not currently available to rework it.

I have filed issue #3557 to track replacing this PR with a modernized update so we can close out this PR.

**Pull request closed without merging**
