### PR TITLE
- updates agenda workflow so it closes older agenda issues automatically

### PR DESCRIPTION
**Pull request by baywet**
related #3420

### CODE REVIEW

**Comment by lornajane** [comment]
How long will it leave the issues open for? I would suggest something over 2 weeks, so we can always look at the previous meeting notes, even if we skip a meeting one week.

**Comment by baywet** [comment]
@lornajane right now it closes the issue as soon as the date in the title is passed, but runs only every week, so that should give us a week effectively.
We could introduce a delay if the TDC decides it.

**Comment by baywet** [comment]
Notes from the meeting:
- wait 10 days before close the issue.
- look into unpinning the issue as we close them.

**Comment by baywet** [comment]
@lornajane @darrelmiller @MikeRalphson @webron : 
- added the delay of 10 days before closing the agenda item
- added pinning/unpinning the issues

I think this is ready to merge.

**Review by darrelmiller — APPROVED** [review]

**Review by earth2marsh — APPROVED** [review]

**Pull request merged**
