### PR TITLE
Define a quoting rule for yaml examples.  #1720.

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

Define a quoting rules for yaml samples.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
@darrelmiller did you intend this guidance to make it into the spec? In any case it looks like a breaking change, so would have to wait for v4.0

**Comment by darrelmiller** [comment]
@MikeRalphson My intent with the rule was for it to be guidance for us writing the specification.  I don't think this should be a rule imposed on OpenAPI description writers.  I have no desire to try and invent a new YAML subset.

**Comment by MikeRalphson** [comment]
Just checking!

**Comment by MikeRalphson** [comment]
Closing as not intended to be part of the spec.

**Pull request closed without merging**
