### PR TITLE
Update ReSpec versions for Arazzo

### PR DESCRIPTION
**Pull request by ncaidin**
This pull request is automatically triggered by GitHub action `respec`.

The versions/v*.md files of the Arazzo Specification have changed, so the HTML files are automatically being regenerated.

### CODE REVIEW

**Comment by frankkilcommins** [comment]
@handrews @Bellangelo if you like what you see re the improved RFC fragments links, I can issue a PR against the OAS repo for the script changes.

See https://github.com/OAI/Arazzo-Specification/pull/199/files for more details

**Comment by handrews** [comment]
@frankkilcommins any idea why the github-actions bot closed this?

**Comment by handrews** [comment]
Reopening so people see this, but let's not merge until we figure out what the bot was doing.

**Comment by handrews** [comment]
or not, because the bot deleted the branch.  The AI revolt is here!  All is lost!  😛

**Comment by frankkilcommins** [comment]
@handrews I think I see the problem. There is a clash with the `respec` action on the `OpenAPI-Specification` repo and the `Arazzo-Specification`. Both jobs create branches of the same name and take it over if already existing. 

See run https://github.com/OAI/OpenAPI-Specification/actions/runs/9421774871/job/25956585879 which was triggered by some of your good work.

I'll create an issue on the Arazzo repo to use a specification specific branch name to avoid cross spec repo collisions.

**Comment by frankkilcommins** [comment]
See https://github.com/OAI/Arazzo-Specification/issues/200

**Pull request closed without merging**
