### PR TITLE
Release v3.0.4

### PR DESCRIPTION
**Pull request by ralfhandl**
This PR will merge `v3.0.4-dev` into `main`.

Still to do:
- [x] Write Release Notes: @lornajane, @handrews
  - #4095
- [x] Merge last-minute PRs 
  - #4077
  - #4078
  - #4081
  - #4086
  - #4090
  - #4100

### CODE REVIEW

**Review by darrelmiller — APPROVED** [review]
This is quite an incredible set of updates.  Thank you to all the people that contributed, with a special call out to Henry Andrews who has added so many clarifications to this document.

**Review by limck5856 — APPROVED** [review]

**Review by limck5856 — APPROVED** [review]

**Review by darrelmiller — APPROVED** [review]

**Comment by miqui** [comment]
Looks good to me. (approved)

**Review by lornajane — APPROVED** [review]

**Review by earth2marsh — DISMISSED** [review]

**Review by earth2marsh — APPROVED** [review]

**Review by darrelmiller — DISMISSED** [review]

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Comment by lornajane** [comment]
Approved!

**Review by miqui — APPROVED** [review]

**Review by lornajane — APPROVED** [review]

**Review by mikekistler — APPROVED** [review]
Looks good. 👍 

I approve this for release.

**Pull request merged**
