### PR TITLE
fix(docs): Update Encoding Object example

### PR DESCRIPTION
**Pull request by jeremyfiel**
closes https://github.com/OAI/OpenAPI-Specification/issues/3170

### CODE REVIEW

**Comment by webron** [comment]
Thanks for the fix, @jeremyfiel. 
Unfortunately, we can't modify files that have already been published and can only modify minor versions.
It looks like we don't have a 3.0.4 branch but I can create one if you want.

**Comment by jeremyfiel** [comment]
Hi Ron,

This is not a patch update, only a docs issue to explain the example
correctly. I don't believe that would require anew version, would it?

**Comment by webron** [comment]
Unfortunately, it would. Anything under the `versions` directory cannot be updated once published, we can only add new versions.

**Comment by jeremyfiel** [comment]
are there any other errata in the works?

**Comment by webron** [comment]
I don't see anything for 3.0 (there is for 3.1), but happy to start one if needed.

**Comment by jeremyfiel** [comment]
since it was updated in 3.1.x.  I guess there's no burning reason to create a new patch version. There is no behavior change.

**Comment by handrews** [comment]
I have a couple of proposals for a quick 3.0.4.  @webron unless you'd rather I did not, I will tag the issue for this PR with the 3.0.4 label and also the other clarifications/bugfixes I've noticed recently.

**Comment by webron** [comment]
I don't see a technical reason not to release 3.0.4. We'll potentially retire 3.0.X after the next minor/major version is released.

**Comment by handrews** [comment]
@jeremyfiel there's now a v3.0.4-dev branch with a `versions/3.0.4.md` file.  This PR has been re-targeted to that branch which is why it shows a bunch of extra commits (those are the post-3.0.3 commits on main, which are not relevant to `3.0.4.md`).

You'll want to either close this and open a new PR, or edit the commit to only apply to `3.0.4.md`, rebase it on top of the v3.0.4-dev branch, and force-push.

**Comment by jeremyfiel** [comment]
ok. probably easier and cleaner to close and make a new one. will do so

**Pull request closed without merging**
