### PR TITLE
whitespace and quoting fixes in json and yaml examples (v3.1.1)

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by lornajane** [comment]
The build failed here because of an outdated dependency in one of the workflows. I recommend rebasing the branch and checking the build passes before merging (and also for the "sister" pull request to this one)

**Comment by karenetheridge** [comment]
rebased.

**Comment by handrews** [comment]
I re-ran the failed check using the environment from main (see #3554) and it passed.  This is safe to merge.

**Comment by karenetheridge** [comment]
rebased!

**Review by handrews — APPROVED** [review]

**Pull request merged**
